(define (last-char str)
(string-ref str (- (string-length str) 1)))
(define (last word)
  (last-char (symbol->string word))
)

(define (ends-e sentence)
  (if (equal? sentence '())
    '()
    (if (equal? (last (car sentence)) #\e)
      (cons (car sentence) (ends-e (cdr sentence)))
      (ends-e (cdr sentence))
    )
  )
)
(define main (display (ends-e '(please put the salami above the blue elephant))))